# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\D8W\Python\ths\NashFlowComputation\source\ui\mainWdw.ui'
#
# Created: Mon May 22 12:41:29 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1292, 1016)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.plotFrame = QtGui.QFrame(self.tab)
        self.plotFrame.setGeometry(QtCore.QRect(10, 10, 631, 411))
        self.plotFrame.setFrameShape(QtGui.QFrame.Box)
        self.plotFrame.setFrameShadow(QtGui.QFrame.Plain)
        self.plotFrame.setObjectName("plotFrame")
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(650, 0, 121, 361))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(0, 80, 68, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(0, 20, 68, 21))
        self.label_5.setObjectName("label_5")
        self.tailLineEdit = QtGui.QLineEdit(self.groupBox)
        self.tailLineEdit.setGeometry(QtCore.QRect(0, 40, 121, 27))
        self.tailLineEdit.setObjectName("tailLineEdit")
        self.headLineEdit = QtGui.QLineEdit(self.groupBox)
        self.headLineEdit.setGeometry(QtCore.QRect(0, 100, 121, 27))
        self.headLineEdit.setObjectName("headLineEdit")
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(0, 140, 81, 21))
        self.label_6.setObjectName("label_6")
        self.transitTimeLineEdit = QtGui.QLineEdit(self.groupBox)
        self.transitTimeLineEdit.setGeometry(QtCore.QRect(0, 160, 121, 27))
        self.transitTimeLineEdit.setObjectName("transitTimeLineEdit")
        self.capacityLineEdit = QtGui.QLineEdit(self.groupBox)
        self.capacityLineEdit.setGeometry(QtCore.QRect(0, 220, 121, 27))
        self.capacityLineEdit.setObjectName("capacityLineEdit")
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(0, 200, 81, 21))
        self.label_7.setObjectName("label_7")
        self.updateEdgeButton = QtGui.QPushButton(self.groupBox)
        self.updateEdgeButton.setGeometry(QtCore.QRect(0, 260, 121, 41))
        self.updateEdgeButton.setAutoDefault(False)
        self.updateEdgeButton.setDefault(False)
        self.updateEdgeButton.setFlat(False)
        self.updateEdgeButton.setObjectName("updateEdgeButton")
        self.deleteEdgeButton = QtGui.QPushButton(self.groupBox)
        self.deleteEdgeButton.setGeometry(QtCore.QRect(0, 310, 121, 41))
        self.deleteEdgeButton.setAutoDefault(False)
        self.deleteEdgeButton.setDefault(False)
        self.deleteEdgeButton.setFlat(False)
        self.deleteEdgeButton.setObjectName("deleteEdgeButton")
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(790, 0, 131, 301))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(0, 20, 68, 21))
        self.label.setObjectName("label")
        self.nodeNameLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.nodeNameLineEdit.setGeometry(QtCore.QRect(0, 40, 121, 27))
        self.nodeNameLineEdit.setObjectName("nodeNameLineEdit")
        self.nodeXLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.nodeXLineEdit.setGeometry(QtCore.QRect(0, 100, 121, 27))
        self.nodeXLineEdit.setObjectName("nodeXLineEdit")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(0, 80, 68, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(0, 140, 68, 21))
        self.label_3.setObjectName("label_3")
        self.nodeYLineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.nodeYLineEdit.setGeometry(QtCore.QRect(0, 160, 121, 27))
        self.nodeYLineEdit.setObjectName("nodeYLineEdit")
        self.updateNodeButton = QtGui.QPushButton(self.groupBox_2)
        self.updateNodeButton.setGeometry(QtCore.QRect(0, 200, 121, 41))
        self.updateNodeButton.setAutoDefault(False)
        self.updateNodeButton.setDefault(False)
        self.updateNodeButton.setFlat(False)
        self.updateNodeButton.setObjectName("updateNodeButton")
        self.deleteNodeButton = QtGui.QPushButton(self.groupBox_2)
        self.deleteNodeButton.setGeometry(QtCore.QRect(0, 250, 121, 41))
        self.deleteNodeButton.setAutoDefault(False)
        self.deleteNodeButton.setDefault(False)
        self.deleteNodeButton.setFlat(False)
        self.deleteNodeButton.setObjectName("deleteNodeButton")
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 430, 921, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(770, 20, 91, 17))
        self.label_8.setObjectName("label_8")
        self.inflowLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.inflowLineEdit.setGeometry(QtCore.QRect(770, 40, 113, 27))
        self.inflowLineEdit.setObjectName("inflowLineEdit")
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(0, 20, 121, 17))
        self.label_9.setObjectName("label_9")
        self.outputDirectoryLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.outputDirectoryLineEdit.setGeometry(QtCore.QRect(0, 40, 601, 27))
        self.outputDirectoryLineEdit.setObjectName("outputDirectoryLineEdit")
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(770, 80, 141, 17))
        self.label_10.setObjectName("label_10")
        self.intervalsLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.intervalsLineEdit.setGeometry(QtCore.QRect(770, 100, 113, 27))
        self.intervalsLineEdit.setObjectName("intervalsLineEdit")
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(0, 80, 121, 17))
        self.label_11.setObjectName("label_11")
        self.templateFileLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.templateFileLineEdit.setGeometry(QtCore.QRect(0, 100, 601, 27))
        self.templateFileLineEdit.setObjectName("templateFileLineEdit")
        self.outputDirectoryPushButton = QtGui.QPushButton(self.groupBox_3)
        self.outputDirectoryPushButton.setGeometry(QtCore.QRect(610, 40, 131, 27))
        self.outputDirectoryPushButton.setObjectName("outputDirectoryPushButton")
        self.templateFilePushButton = QtGui.QPushButton(self.groupBox_3)
        self.templateFilePushButton.setGeometry(QtCore.QRect(610, 100, 131, 27))
        self.templateFilePushButton.setObjectName("templateFilePushButton")
        self.scipPathLineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.scipPathLineEdit.setGeometry(QtCore.QRect(0, 160, 601, 27))
        self.scipPathLineEdit.setObjectName("scipPathLineEdit")
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(0, 140, 121, 17))
        self.label_12.setObjectName("label_12")
        self.scipPathPushButton = QtGui.QPushButton(self.groupBox_3)
        self.scipPathPushButton.setGeometry(QtCore.QRect(610, 160, 131, 27))
        self.scipPathPushButton.setObjectName("scipPathPushButton")
        self.computeFlowPushButton = QtGui.QPushButton(self.tab)
        self.computeFlowPushButton.setGeometry(QtCore.QRect(780, 570, 141, 51))
        self.computeFlowPushButton.setAutoDefault(False)
        self.computeFlowPushButton.setDefault(False)
        self.computeFlowPushButton.setFlat(False)
        self.computeFlowPushButton.setObjectName("computeFlowPushButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(670, 0, 291, 521))
        self.groupBox_5.setObjectName("groupBox_5")
        self.plotEdgeQueueWidget = QtGui.QWidget(self.groupBox_5)
        self.plotEdgeQueueWidget.setGeometry(QtCore.QRect(10, 20, 251, 241))
        self.plotEdgeQueueWidget.setObjectName("plotEdgeQueueWidget")
        self.plotEdgeInflowWidget = QtGui.QWidget(self.groupBox_5)
        self.plotEdgeInflowWidget.setGeometry(QtCore.QRect(10, 270, 251, 241))
        self.plotEdgeInflowWidget.setObjectName("plotEdgeInflowWidget")
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(970, 0, 291, 271))
        self.groupBox_6.setObjectName("groupBox_6")
        self.plotNodeLabelWidget = QtGui.QWidget(self.groupBox_6)
        self.plotNodeLabelWidget.setGeometry(QtCore.QRect(10, 20, 251, 241))
        self.plotNodeLabelWidget.setObjectName("plotNodeLabelWidget")
        self.horizontalSlider = QtGui.QSlider(self.tab_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 430, 631, 19))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 460, 651, 431))
        self.groupBox_4.setObjectName("groupBox_4")
        self.plotNTFWidget = QtGui.QWidget(self.groupBox_4)
        self.plotNTFWidget.setGeometry(QtCore.QRect(10, 20, 631, 401))
        self.plotNTFWidget.setObjectName("plotNTFWidget")
        self.groupBox_7 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 10, 651, 441))
        self.groupBox_7.setObjectName("groupBox_7")
        self.plotNashflowWidget = QtGui.QWidget(self.groupBox_7)
        self.plotNashflowWidget.setGeometry(QtCore.QRect(10, 20, 631, 391))
        self.plotNashflowWidget.setObjectName("plotNashflowWidget")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1292, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Graph = QtGui.QAction(MainWindow)
        self.actionLoad_Graph.setObjectName("actionLoad_Graph")
        self.actionSave_Graph = QtGui.QAction(MainWindow)
        self.actionSave_Graph.setObjectName("actionSave_Graph")
        self.actionNew_graph = QtGui.QAction(MainWindow)
        self.actionNew_graph.setObjectName("actionNew_graph")
        self.actionLoad_graph = QtGui.QAction(MainWindow)
        self.actionLoad_graph.setObjectName("actionLoad_graph")
        self.actionSave_graph = QtGui.QAction(MainWindow)
        self.actionSave_graph.setObjectName("actionSave_graph")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew_graph)
        self.menuFile.addAction(self.actionLoad_graph)
        self.menuFile.addAction(self.actionSave_graph)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Edge", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Head", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Tail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Transit time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Capacity", None, QtGui.QApplication.UnicodeUTF8))
        self.updateEdgeButton.setText(QtGui.QApplication.translate("MainWindow", "Update/add edge", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteEdgeButton.setText(QtGui.QApplication.translate("MainWindow", "Delete edge", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Node", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "X-position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Y-position", None, QtGui.QApplication.UnicodeUTF8))
        self.updateNodeButton.setText(QtGui.QApplication.translate("MainWindow", "Update node", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteNodeButton.setText(QtGui.QApplication.translate("MainWindow", "Delete node", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Config", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Inflow Rate", None, QtGui.QApplication.UnicodeUTF8))
        self.inflowLineEdit.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Output directory", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "# Intervals (-1 = all)", None, QtGui.QApplication.UnicodeUTF8))
        self.intervalsLineEdit.setText(QtGui.QApplication.translate("MainWindow", "-1", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Template file", None, QtGui.QApplication.UnicodeUTF8))
        self.outputDirectoryPushButton.setText(QtGui.QApplication.translate("MainWindow", "Select directory", None, QtGui.QApplication.UnicodeUTF8))
        self.templateFilePushButton.setText(QtGui.QApplication.translate("MainWindow", "Select file", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "SCIP path", None, QtGui.QApplication.UnicodeUTF8))
        self.scipPathPushButton.setText(QtGui.QApplication.translate("MainWindow", "Select binary", None, QtGui.QApplication.UnicodeUTF8))
        self.computeFlowPushButton.setText(QtGui.QApplication.translate("MainWindow", "Compute Nashflow", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Create/Load Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Edge", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Node", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("MainWindow", "Normalized Thin Flows", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Nash Flow over Time", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Compute Nash flow", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Graph.setText(QtGui.QApplication.translate("MainWindow", "Load Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_Graph.setText(QtGui.QApplication.translate("MainWindow", "Save Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew_graph.setText(QtGui.QApplication.translate("MainWindow", "New graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_graph.setText(QtGui.QApplication.translate("MainWindow", "Load graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_graph.setText(QtGui.QApplication.translate("MainWindow", "Save graph", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))

